import { AchievementMetric } from '@prisma/client';

type SeedAchievement = {
  key: string;
  name: string;
  description: string;
  metric: AchievementMetric;
  threshold: number;
  rewardXp: number;
  rewardBits: number;
  rewardCosmeticKey?: string;
};

export const STARTER_ACHIEVEMENTS: SeedAchievement[] = [
  // Píxeles
  {
    key: 'pixels_100',
    name: 'Primeros trazos',
    description: 'Coloca 100 píxeles.',
    metric: 'PIXELS_PLACED',
    threshold: 100,
    rewardXp: 50,
    rewardBits: 20,
  },
  {
    key: 'pixels_1000',
    name: 'Pintor dedicado',
    description: 'Coloca 1 000 píxeles.',
    metric: 'PIXELS_PLACED',
    threshold: 1000,
    rewardXp: 150,
    rewardBits: 75,
  },
  {
    key: 'pixels_10000',
    name: 'Maestro del lienzo',
    description: 'Coloca 10 000 píxeles.',
    metric: 'PIXELS_PLACED',
    threshold: 10000,
    rewardXp: 500,
    rewardBits: 300,
  },
  {
    key: 'pixels_50000',
    name: 'Artesano incansable',
    description: 'Coloca 50 000 píxeles.',
    metric: 'PIXELS_PLACED',
    threshold: 50000,
    rewardXp: 1200,
    rewardBits: 700,
  },
  {
    key: 'pixels_100000',
    name: 'Leyenda del píxel',
    description: 'Coloca 100 000 píxeles.',
    metric: 'PIXELS_PLACED',
    threshold: 100000,
    rewardXp: 2000,
    rewardBits: 1200,
  },
  {
    key: 'pixels_500000',
    name: 'Fuerza imparable',
    description: 'Coloca 500 000 píxeles.',
    metric: 'PIXELS_PLACED',
    threshold: 500000,
    rewardXp: 4000,
    rewardBits: 3000,
  },
  {
    key: 'pixels_1000000',
    name: 'Un millón de trazos',
    description: 'Coloca 1 000 000 de píxeles.',
    metric: 'PIXELS_PLACED',
    threshold: 1000000,
    rewardXp: 8000,
    rewardBits: 6000,
  },
  // Publicaciones
  {
    key: 'pubs_1',
    name: 'Primera obra',
    description: 'Crea tu primera publicación.',
    metric: 'PUBLICATIONS_CREATED',
    threshold: 1,
    rewardXp: 30,
    rewardBits: 15,
  },
  {
    key: 'pubs_10',
    name: 'Galería',
    description: 'Crea 10 publicaciones.',
    metric: 'PUBLICATIONS_CREATED',
    threshold: 10,
    rewardXp: 200,
    rewardBits: 100,
  },
  {
    key: 'pubs_25',
    name: 'Curador',
    description: 'Crea 25 publicaciones.',
    metric: 'PUBLICATIONS_CREATED',
    threshold: 25,
    rewardXp: 400,
    rewardBits: 250,
  },
  {
    key: 'pubs_100',
    name: 'Museo viviente',
    description: 'Crea 100 publicaciones.',
    metric: 'PUBLICATIONS_CREATED',
    threshold: 100,
    rewardXp: 1200,
    rewardBits: 800,
  },
  // Likes recibidos
  {
    key: 'likes_10',
    name: 'Primeros aplausos',
    description: 'Recibe 10 likes en tus obras.',
    metric: 'LIKES_RECEIVED',
    threshold: 10,
    rewardXp: 60,
    rewardBits: 30,
  },
  {
    key: 'likes_50',
    name: 'Reconocido',
    description: 'Recibe 50 likes en tus obras.',
    metric: 'LIKES_RECEIVED',
    threshold: 50,
    rewardXp: 200,
    rewardBits: 100,
  },
  {
    key: 'likes_500',
    name: 'Favorito del público',
    description: 'Recibe 500 likes en tus obras.',
    metric: 'LIKES_RECEIVED',
    threshold: 500,
    rewardXp: 600,
    rewardBits: 400,
  },
  {
    key: 'likes_1000',
    name: 'Ídolo',
    description: 'Recibe 1 000 likes en tus obras.',
    metric: 'LIKES_RECEIVED',
    threshold: 1000,
    rewardXp: 1000,
    rewardBits: 700,
  },
  {
    key: 'likes_5000',
    name: 'Fenómeno viral',
    description: 'Recibe 5 000 likes en tus obras.',
    metric: 'LIKES_RECEIVED',
    threshold: 5000,
    rewardXp: 3000,
    rewardBits: 2500,
  },
  // Nivel alcanzado
  {
    key: 'level_5',
    name: 'Subiendo',
    description: 'Alcanza el nivel 5.',
    metric: 'LEVEL_REACHED',
    threshold: 5,
    rewardXp: 0,
    rewardBits: 100,
  },
  {
    key: 'level_10',
    name: 'En racha',
    description: 'Alcanza el nivel 10.',
    metric: 'LEVEL_REACHED',
    threshold: 10,
    rewardXp: 0,
    rewardBits: 250,
  },
  {
    key: 'level_25',
    name: 'Veterano',
    description: 'Alcanza el nivel 25.',
    metric: 'LEVEL_REACHED',
    threshold: 25,
    rewardXp: 0,
    rewardBits: 600,
  },
  {
    key: 'level_50',
    name: 'Élite',
    description: 'Alcanza el nivel 50.',
    metric: 'LEVEL_REACHED',
    threshold: 50,
    rewardXp: 0,
    rewardBits: 1500,
  },
  {
    key: 'level_75',
    name: 'Gran maestro',
    description: 'Alcanza el nivel 75.',
    metric: 'LEVEL_REACHED',
    threshold: 75,
    rewardXp: 0,
    rewardBits: 3000,
  },
  {
    key: 'level_100',
    name: 'Leyenda viva',
    description: 'Alcanza el nivel 100.',
    metric: 'LEVEL_REACHED',
    threshold: 100,
    rewardXp: 0,
    rewardBits: 6000,
  },
  // Colección de cosméticos
  {
    key: 'collect_1',
    name: 'Estrena estilo',
    description: 'Consigue tu primer cosmético.',
    metric: 'COSMETICS_OWNED',
    threshold: 1,
    rewardXp: 0,
    rewardBits: 50,
  },
  {
    key: 'collect_10',
    name: 'Coleccionista',
    description: 'Reúne 10 cosméticos.',
    metric: 'COSMETICS_OWNED',
    threshold: 10,
    rewardXp: 100,
    rewardBits: 150,
  },
  {
    key: 'collect_25',
    name: 'Acaparador',
    description: 'Reúne 25 cosméticos.',
    metric: 'COSMETICS_OWNED',
    threshold: 25,
    rewardXp: 300,
    rewardBits: 400,
  },
  {
    key: 'collect_50',
    name: 'Gran coleccionista',
    description: 'Reúne 50 cosméticos.',
    metric: 'COSMETICS_OWNED',
    threshold: 50,
    rewardXp: 600,
    rewardBits: 900,
  },
  // Rareza y paletas
  {
    key: 'legendary_1',
    name: 'Pieza legendaria',
    description: 'Consigue tu primer cosmético legendario.',
    metric: 'LEGENDARY_OWNED',
    threshold: 1,
    rewardXp: 200,
    rewardBits: 300,
  },
  {
    key: 'mythic_1',
    name: 'Mito hecho realidad',
    description: 'Consigue tu primer cosmético mítico.',
    metric: 'MYTHIC_OWNED',
    threshold: 1,
    rewardXp: 500,
    rewardBits: 800,
  },
  {
    key: 'palette_1',
    name: 'Paleta completa',
    description: 'Completa cualquier paleta de colores.',
    metric: 'PALETTE_COMPLETED',
    threshold: 1,
    rewardXp: 150,
    rewardBits: 250,
  },
  // Amigos
  {
    key: 'friends_1',
    name: 'Primer amigo',
    description: 'Haz tu primer amigo.',
    metric: 'FRIENDS',
    threshold: 1,
    rewardXp: 50,
    rewardBits: 50,
  },
  {
    key: 'friends_10',
    name: 'Círculo social',
    description: 'Llega a 10 amigos.',
    metric: 'FRIENDS',
    threshold: 10,
    rewardXp: 200,
    rewardBits: 200,
  },
];
