import { CosmeticType, CosmeticRarity, Prisma } from '@prisma/client';

type ShopCosmetic = {
  key: string;
  type: CosmeticType;
  name: string;
  description: string;
  rarity: CosmeticRarity;
  priceBits: number;
  data?: Prisma.InputJsonValue;
  theme?: string;
};

export const SHOP_COSMETICS: ShopCosmetic[] = [
  // Comunes
  {
    key: 'title_aprendiz',
    type: 'TITLE',
    name: 'Aprendiz',
    description: 'Apenas empiezas tu camino.',
    rarity: 'COMMON',
    priceBits: 120,
  },
  {
    key: 'title_pixelero',
    type: 'TITLE',
    name: 'Pixelero',
    description: 'Pixel a pixel se hace el lienzo.',
    rarity: 'COMMON',
    priceBits: 200,
  },
  {
    key: 'badge_chispa',
    type: 'BADGE',
    name: 'Chispa',
    description: 'Una pequeña chispa creativa.',
    rarity: 'COMMON',
    priceBits: 150,
    data: { icon: 'star' },
  },
  // Raros
  {
    key: 'title_virtuoso',
    type: 'TITLE',
    name: 'Virtuoso',
    description: 'Dominas el arte del pixel.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#4ADE80' },
  },
  {
    key: 'badge_corona',
    type: 'BADGE',
    name: 'Corona',
    description: 'Para quien reina en el lienzo.',
    rarity: 'RARE',
    priceBits: 650,
    data: { icon: 'crown' },
  },
  // Premium
  {
    key: 'title_leyenda_shop',
    type: 'TITLE',
    name: 'Leyenda',
    description: 'Reservado para los grandes.',
    rarity: 'EPIC',
    priceBits: 1200,
    data: { color: '#FF7A1A' },
  },
  // Marcos
  {
    key: 'frame_acero',
    type: 'FRAME',
    name: 'Acero',
    description: 'Un marco sobrio.',
    rarity: 'COMMON',
    priceBits: 220,
    data: { ring: '#A8A8B0' },
  },
  {
    key: 'frame_neon',
    type: 'FRAME',
    name: 'Neón',
    description: 'Brillo de neón alrededor.',
    rarity: 'RARE',
    priceBits: 600,
    data: { ring: 'linear-gradient(135deg,#60A5FA,#A78BFA)' },
  },
  {
    key: 'frame_oro',
    type: 'FRAME',
    name: 'Oro',
    description: 'Solo para los grandes.',
    rarity: 'EPIC',
    priceBits: 1300,
    data: { ring: 'linear-gradient(135deg,#FFD700,#FFA500)' },
  },
  // Fondos
  {
    key: 'bg_menta',
    type: 'BACKGROUND',
    name: 'Menta',
    description: 'Un fondo fresco.',
    rarity: 'COMMON',
    priceBits: 220,
    data: { background: 'linear-gradient(160deg,#1b2b26,#16241f)' },
  },
  {
    key: 'bg_atardecer',
    type: 'BACKGROUND',
    name: 'Atardecer',
    description: 'Tonos de ocaso.',
    rarity: 'RARE',
    priceBits: 650,
    data: { background: 'linear-gradient(160deg,#3a1f2e,#1f1626)' },
  },
  {
    key: 'bg_espacio',
    type: 'BACKGROUND',
    name: 'Espacio',
    description: 'Pierde la mirada en el cosmos.',
    rarity: 'EPIC',
    priceBits: 1300,
    data: { background: 'linear-gradient(160deg,#0f1030,#1a1040)' },
  },
  // Colores exóticos
  {
    key: 'color_tornasol_fuego',
    type: 'COLOR',
    name: 'Tornasol Fuego',
    description: 'Degradado ardiente.',
    rarity: 'RARE',
    priceBits: 200,
    data: {
      token: 'fade:#FF3B3B,#FFD93B',
      swatch: 'linear-gradient(135deg,#FF3B3B,#FFD93B)',
    },
  },
  {
    key: 'color_tornasol_oceano',
    type: 'COLOR',
    name: 'Tornasol Océano',
    description: 'Del turquesa al azul profundo.',
    rarity: 'RARE',
    priceBits: 200,
    data: {
      token: 'fade:#22D3EE,#3B5BFF',
      swatch: 'linear-gradient(135deg,#22D3EE,#3B5BFF)',
    },
  },
  {
    key: 'color_plata',
    type: 'COLOR',
    name: 'Plata',
    description: 'Brillo metálico plateado.',
    rarity: 'RARE',
    priceBits: 250,
    data: {
      token: 'fade:#FFFFFF,#8A8F94',
      swatch: 'linear-gradient(135deg,#FFFFFF,#C0C0C0,#8A8F94)',
    },
  },
  {
    key: 'color_oro',
    type: 'COLOR',
    name: 'Oro',
    description: 'Brillo metálico dorado.',
    rarity: 'EPIC',
    priceBits: 300,
    data: {
      token: 'fade:#FFF3B0,#B8860B',
      swatch: 'linear-gradient(135deg,#FFF3B0,#FFD700,#B8860B)',
    },
  },
  {
    key: 'color_arcoiris',
    type: 'COLOR',
    name: 'Arcoíris',
    description: 'Todo el espectro.',
    rarity: 'EPIC',
    priceBits: 350,
    data: {
      token: 'rainbow',
      swatch: 'linear-gradient(90deg,#f00,#ff0,#0f0,#0ff,#00f,#f0f)',
    },
  },
  // === Títulos nuevos (evergreen + estética) ===
  {
    key: 'title_artista',
    type: 'TITLE',
    name: 'Artista',
    description: 'Tu lienzo habla por ti.',
    rarity: 'COMMON',
    priceBits: 200,
  },
  {
    key: 'title_creador',
    type: 'TITLE',
    name: 'Creador',
    description: 'Das vida al lienzo.',
    rarity: 'RARE',
    priceBits: 550,
    data: { color: '#60A5FA' },
  },
  {
    key: 'title_visionario',
    type: 'TITLE',
    name: 'Visionario',
    description: 'Ves lo que otros no.',
    rarity: 'EPIC',
    priceBits: 1200,
    data: { color: '#A78BFA' },
  },
  {
    key: 'title_y2k',
    type: 'TITLE',
    name: 'Y2K Kid',
    description: 'Nacido para el nuevo milenio.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#22D3EE' },
    theme: 'y2k',
  },
  {
    key: 'title_vaporwave',
    type: 'TITLE',
    name: 'Vaporwave',
    description: 'Estética sobre todo.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#FF88FF' },
    theme: 'vaporwave',
  },

  // === Títulos de temporada ===
  {
    key: 'title_halloween',
    type: 'TITLE',
    name: 'Alma en Pena',
    description: 'Vaga entre los pixeles.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#FF8800' },
    theme: 'halloween',
  },
  {
    key: 'title_navidad',
    type: 'TITLE',
    name: 'Espíritu Navideño',
    description: 'Pura magia decembrina.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#EF4444' },
    theme: 'navidad',
  },
  {
    key: 'title_invierno',
    type: 'TITLE',
    name: 'Corazón de Hielo',
    description: 'Frío por fuera, arte por dentro.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { color: '#88FFFF' },
    theme: 'invierno',
  },

  // === Marcos de temporada y estética ===
  {
    key: 'frame_calabaza',
    type: 'FRAME',
    name: 'Calabaza',
    description: 'Aroma a otoño.',
    rarity: 'COMMON',
    priceBits: 250,
    data: { ring: 'linear-gradient(135deg,#FF8800,#7C2D12)' },
    theme: 'halloween',
  },
  {
    key: 'frame_telarana',
    type: 'FRAME',
    name: 'Telaraña',
    description: 'Tejida en la penumbra.',
    rarity: 'RARE',
    priceBits: 600,
    data: { ring: 'linear-gradient(135deg,#6B21A8,#FF8800)' },
    theme: 'halloween',
  },
  {
    key: 'frame_navidad',
    type: 'FRAME',
    name: 'Luces Navideñas',
    description: 'Brillo de fiesta.',
    rarity: 'RARE',
    priceBits: 650,
    data: { ring: 'linear-gradient(135deg,#EF4444,#22C55E)' },
    theme: 'navidad',
  },
  {
    key: 'frame_escarcha',
    type: 'FRAME',
    name: 'Escarcha',
    description: 'Cristales de hielo.',
    rarity: 'COMMON',
    priceBits: 250,
    data: { ring: 'linear-gradient(135deg,#A5F3FC,#3B82F6)' },
    theme: 'invierno',
  },
  {
    key: 'frame_synthwave',
    type: 'FRAME',
    name: 'Synthwave',
    description: 'Directo de los 80.',
    rarity: 'RARE',
    priceBits: 650,
    data: { ring: 'linear-gradient(135deg,#FF2E97,#7C3AED)' },
    theme: 'synthwave',
  },
  {
    key: 'frame_vaporwave',
    type: 'FRAME',
    name: 'Vaporwave',
    description: 'Rosa y turquesa eternos.',
    rarity: 'RARE',
    priceBits: 650,
    data: { ring: 'linear-gradient(135deg,#FF88FF,#22D3EE)' },
    theme: 'vaporwave',
  },
  {
    key: 'frame_glitch',
    type: 'FRAME',
    name: 'Glitch',
    description: 'Error... o estilo.',
    rarity: 'RARE',
    priceBits: 600,
    data: { ring: 'linear-gradient(135deg,#22D3EE,#FF2E97)' },
    theme: 'y2k',
  },
  {
    key: 'frame_prisma',
    type: 'FRAME',
    name: 'Prisma',
    description: 'Todo el espectro alrededor.',
    rarity: 'EPIC',
    priceBits: 1300,
    data: { ring: 'linear-gradient(135deg,#f00,#ff0,#0f0,#0ff,#00f,#f0f)' },
  },

  // === Fondos de temporada y estética ===
  {
    key: 'bg_halloween',
    type: 'BACKGROUND',
    name: 'Noche de Brujas',
    description: 'Sombras y calabazas.',
    rarity: 'RARE',
    priceBits: 650,
    data: { background: 'linear-gradient(160deg,#1a0f2e,#2e1a0f)' },
    theme: 'halloween',
  },
  {
    key: 'bg_navidad',
    type: 'BACKGROUND',
    name: 'Nochebuena',
    description: 'Calidez decembrina.',
    rarity: 'RARE',
    priceBits: 650,
    data: { background: 'linear-gradient(160deg,#0f2417,#2e1414)' },
    theme: 'navidad',
  },
  {
    key: 'bg_invierno',
    type: 'BACKGROUND',
    name: 'Ventisca',
    description: 'Azul gélido.',
    rarity: 'COMMON',
    priceBits: 250,
    data: { background: 'linear-gradient(160deg,#16243a,#0f1a2e)' },
    theme: 'invierno',
  },
  {
    key: 'bg_otono',
    type: 'BACKGROUND',
    name: 'Otoño',
    description: 'Hojas que caen.',
    rarity: 'COMMON',
    priceBits: 250,
    data: { background: 'linear-gradient(160deg,#2e1c0f,#241408)' },
    theme: 'otono',
  },
  {
    key: 'bg_aurora',
    type: 'BACKGROUND',
    name: 'Aurora',
    description: 'Luces del norte.',
    rarity: 'EPIC',
    priceBits: 1300,
    data: { background: 'linear-gradient(160deg,#0f2e2a,#1a0f3a)' },
    theme: 'aurora',
  },
  {
    key: 'bg_synthwave',
    type: 'BACKGROUND',
    name: 'Synthwave',
    description: 'Sol de neón al atardecer.',
    rarity: 'RARE',
    priceBits: 700,
    data: { background: 'linear-gradient(160deg,#2a0f3a,#3a0f2e)' },
    theme: 'synthwave',
  },
  {
    key: 'bg_vaporwave',
    type: 'BACKGROUND',
    name: 'Vaporwave',
    description: 'A E S T H E T I C.',
    rarity: 'RARE',
    priceBits: 700,
    data: { background: 'linear-gradient(160deg,#2e0f3a,#0f2a3a)' },
    theme: 'vaporwave',
  },

  // === Colores exóticos nuevos ===
  {
    key: 'color_synthwave',
    type: 'COLOR',
    name: 'Synthwave',
    description: 'Del rosa neón al violeta.',
    rarity: 'RARE',
    priceBits: 250,
    data: {
      token: 'fade:#FF2E97,#7C3AED',
      swatch: 'linear-gradient(135deg,#FF2E97,#7C3AED)',
    },
    theme: 'synthwave',
  },
  {
    key: 'color_vaporwave',
    type: 'COLOR',
    name: 'Vaporwave',
    description: 'Rosa y turquesa.',
    rarity: 'RARE',
    priceBits: 250,
    data: {
      token: 'fade:#FF88FF,#22D3EE',
      swatch: 'linear-gradient(135deg,#FF88FF,#22D3EE)',
    },
    theme: 'vaporwave',
  },
  {
    key: 'color_galaxia',
    type: 'COLOR',
    name: 'Galaxia',
    description: 'Profundidades del cosmos.',
    rarity: 'RARE',
    priceBits: 250,
    data: {
      token: 'fade:#3B0764,#1E3A8A',
      swatch: 'linear-gradient(135deg,#3B0764,#1E3A8A)',
    },
    theme: 'galaxia',
  },
  {
    key: 'color_aurora',
    type: 'COLOR',
    name: 'Aurora',
    description: 'Verde y violeta boreal.',
    rarity: 'RARE',
    priceBits: 300,
    data: {
      token: 'fade:#34D399,#8B5CF6',
      swatch: 'linear-gradient(135deg,#34D399,#8B5CF6)',
    },
    theme: 'aurora',
  },
  {
    key: 'color_otono',
    type: 'COLOR',
    name: 'Otoño',
    description: 'Del ámbar al carmesí.',
    rarity: 'RARE',
    priceBits: 200,
    data: {
      token: 'fade:#F59E0B,#7C2D12',
      swatch: 'linear-gradient(135deg,#F59E0B,#7C2D12)',
    },
    theme: 'otono',
  },
  {
    key: 'color_lava',
    type: 'COLOR',
    name: 'Lava',
    description: 'Roca fundida.',
    rarity: 'RARE',
    priceBits: 200,
    data: {
      token: 'fade:#FBBF24,#DC2626',
      swatch: 'linear-gradient(135deg,#FBBF24,#DC2626)',
    },
    theme: 'lava',
  },
  // === Insignias nuevas (evergreen) ===
  {
    key: 'badge_corazon',
    type: 'BADGE',
    name: 'Corazón',
    description: 'Pintas con cariño.',
    rarity: 'COMMON',
    priceBits: 150,
    data: { icon: 'heart' },
  },
  {
    key: 'badge_michi',
    type: 'BADGE',
    name: 'Michi',
    description: 'El internet ama los gatos.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'cat' },
  },
  {
    key: 'badge_rayo',
    type: 'BADGE',
    name: 'Rayo',
    description: 'Rápido como el relámpago.',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'bolt' },
  },
  {
    key: 'badge_cohete',
    type: 'BADGE',
    name: 'Cohete',
    description: 'Hasta el infinito.',
    rarity: 'RARE',
    priceBits: 550,
    data: { icon: 'rocket' },
  },
  {
    key: 'badge_fuego',
    type: 'BADGE',
    name: 'En Llamas',
    description: 'Estás que ardes.',
    rarity: 'RARE',
    priceBits: 550,
    data: { icon: 'fire' },
  },
  {
    key: 'badge_trofeo',
    type: 'BADGE',
    name: 'Trofeo',
    description: 'Para los campeones.',
    rarity: 'RARE',
    priceBits: 600,
    data: { icon: 'trophy' },
  },
  {
    key: 'badge_diamante',
    type: 'BADGE',
    name: 'Diamante',
    description: 'Brillas distinto.',
    rarity: 'EPIC',
    priceBits: 1200,
    data: { icon: 'diamond' },
  },

  // === Insignias de temporada ===
  {
    key: 'badge_calabaza',
    type: 'BADGE',
    name: 'Calabaza',
    description: 'Dulce o truco.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'pumpkin' },
    theme: 'halloween',
  },
  {
    key: 'badge_fantasma',
    type: 'BADGE',
    name: 'Fantasma',
    description: 'Buu.',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'ghost' },
    theme: 'halloween',
  },
  {
    key: 'badge_calavera',
    type: 'BADGE',
    name: 'Calavera',
    description: 'Espíritu del Día de Muertos.',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'skull' },
    theme: 'dia_muertos',
  },
  {
    key: 'badge_copo',
    type: 'BADGE',
    name: 'Copo de Nieve',
    description: 'Único como tú.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'snowflake' },
    theme: 'invierno',
  },
  {
    key: 'badge_regalo',
    type: 'BADGE',
    name: 'Regalo',
    description: 'Algo bajo el árbol.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'gift' },
    theme: 'navidad',
  },
  {
    key: 'badge_trebol',
    type: 'BADGE',
    name: 'Trébol',
    description: 'La suerte te acompaña.',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'clover' },
    theme: 'san_patricio',
  },

  // === Insignias de estética / internet ===
  {
    key: 'badge_alien',
    type: 'BADGE',
    name: 'Alien',
    description: 'No eres de este mundo.',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'alien' },
    theme: 'meme',
  },
  {
    key: 'badge_arcoiris',
    type: 'BADGE',
    name: 'Arcoíris',
    description: 'Color en todas partes.',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'rainbow' },
  },
  {
    key: 'badge_flor',
    type: 'BADGE',
    name: 'Florecita',
    description: 'Cottagecore vibes.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'flower' },
    theme: 'cottagecore',
  },

  // === Títulos meme / internet (texto original, sin IP de terceros) ===
  {
    key: 'title_main_character',
    type: 'TITLE',
    name: 'Main Character',
    description: 'El mundo gira a tu alrededor.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#F472B6' },
    theme: 'meme',
  },
  {
    key: 'title_npc',
    type: 'TITLE',
    name: 'NPC',
    description: 'Solo sigues el guion.',
    rarity: 'COMMON',
    priceBits: 200,
    theme: 'meme',
  },
  {
    key: 'title_touch_grass',
    type: 'TITLE',
    name: 'Touch Grass',
    description: 'Quizá deberías salir un rato.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#4ADE80' },
    theme: 'meme',
  },
  {
    key: 'title_pov',
    type: 'TITLE',
    name: 'POV',
    description: 'Punto de vista.',
    rarity: 'COMMON',
    priceBits: 200,
    theme: 'meme',
  },
  {
    key: 'title_gg',
    type: 'TITLE',
    name: 'GG',
    description: 'Buena partida.',
    rarity: 'COMMON',
    priceBits: 150,
    theme: 'meme',
  },
  // === San Valentín ===
  {
    key: 'title_cupido',
    type: 'TITLE',
    name: 'Cupido',
    description: 'Flechas certeras.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#F472B6' },
    theme: 'san_valentin',
  },
  {
    key: 'badge_flechazo',
    type: 'BADGE',
    name: 'Flechazo',
    description: 'Directo al corazón.',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'heartarrow' },
    theme: 'san_valentin',
  },
  {
    key: 'badge_dos_corazones',
    type: 'BADGE',
    name: 'Dos Corazones',
    description: 'Amor por partida doble.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'twohearts' },
    theme: 'san_valentin',
  },
  {
    key: 'badge_rosa',
    type: 'BADGE',
    name: 'Rosa',
    description: 'Un detalle clásico.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'rose' },
    theme: 'san_valentin',
  },
  {
    key: 'frame_san_valentin',
    type: 'FRAME',
    name: 'Romance',
    description: 'Marco enamorado.',
    rarity: 'RARE',
    priceBits: 600,
    data: { ring: 'linear-gradient(135deg,#EF4444,#F472B6)' },
    theme: 'san_valentin',
  },
  {
    key: 'bg_san_valentin',
    type: 'BACKGROUND',
    name: 'San Valentín',
    description: 'Atmósfera romántica.',
    rarity: 'RARE',
    priceBits: 650,
    data: { background: 'linear-gradient(160deg,#2e0f1a,#3a0f24)' },
    theme: 'san_valentin',
  },
  {
    key: 'color_romance',
    type: 'COLOR',
    name: 'Romance',
    description: 'Del rojo al rosa.',
    rarity: 'RARE',
    priceBits: 250,
    data: {
      token: 'fade:#EF4444,#F9A8D4',
      swatch: 'linear-gradient(135deg,#EF4444,#F9A8D4)',
    },
    theme: 'san_valentin',
  },

  // === Verano ===
  {
    key: 'title_verano',
    type: 'TITLE',
    name: 'Sol de Verano',
    description: 'Brillas como agosto.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { color: '#FBBF24' },
    theme: 'verano',
  },
  {
    key: 'badge_sol',
    type: 'BADGE',
    name: 'Sol',
    description: 'Pura energía.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'sun' },
    theme: 'verano',
  },
  {
    key: 'badge_palmera',
    type: 'BADGE',
    name: 'Palmera',
    description: 'Vibras tropicales.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'palm' },
    theme: 'verano',
  },
  {
    key: 'badge_helado',
    type: 'BADGE',
    name: 'Helado',
    description: 'Antes de que se derrita.',
    rarity: 'COMMON',
    priceBits: 150,
    data: { icon: 'icecream' },
    theme: 'verano',
  },
  {
    key: 'frame_verano',
    type: 'FRAME',
    name: 'Verano',
    description: 'Marco soleado.',
    rarity: 'RARE',
    priceBits: 600,
    data: { ring: 'linear-gradient(135deg,#FBBF24,#FB7185)' },
    theme: 'verano',
  },
  {
    key: 'bg_playa',
    type: 'BACKGROUND',
    name: 'Playa',
    description: 'Arena y mar.',
    rarity: 'RARE',
    priceBits: 650,
    data: { background: 'linear-gradient(160deg,#1a2e3a,#2e2a14)' },
    theme: 'verano',
  },
  {
    key: 'color_tropical',
    type: 'COLOR',
    name: 'Tropical',
    description: 'Del sol al mar.',
    rarity: 'RARE',
    priceBits: 250,
    data: {
      token: 'fade:#FBBF24,#22D3EE',
      swatch: 'linear-gradient(135deg,#FBBF24,#22D3EE)',
    },
    theme: 'verano',
  },

  // === Año Nuevo ===
  {
    key: 'title_ano_nuevo',
    type: 'TITLE',
    name: 'Cuenta Regresiva',
    description: '3... 2... 1...',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#FFD700' },
    theme: 'ano_nuevo',
  },
  {
    key: 'badge_fuegos',
    type: 'BADGE',
    name: 'Fuegos Artificiales',
    description: '¡Feliz año!',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'fireworks' },
    theme: 'ano_nuevo',
  },
  {
    key: 'badge_fiesta',
    type: 'BADGE',
    name: 'Fiesta',
    description: 'Que no pare.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'party' },
    theme: 'ano_nuevo',
  },
  {
    key: 'badge_brindis',
    type: 'BADGE',
    name: 'Brindis',
    description: '¡Salud!',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'champagne' },
    theme: 'ano_nuevo',
  },
  {
    key: 'frame_ano_nuevo',
    type: 'FRAME',
    name: 'Año Nuevo',
    description: 'Brillo de medianoche.',
    rarity: 'RARE',
    priceBits: 650,
    data: { ring: 'linear-gradient(135deg,#FFD700,#A78BFA)' },
    theme: 'ano_nuevo',
  },
  {
    key: 'bg_fuegos',
    type: 'BACKGROUND',
    name: 'Fuegos',
    description: 'Cielo de fiesta.',
    rarity: 'RARE',
    priceBits: 700,
    data: { background: 'linear-gradient(160deg,#1a103a,#3a1030)' },
    theme: 'ano_nuevo',
  },

  // === Primavera ===
  {
    key: 'title_primavera',
    type: 'TITLE',
    name: 'Primavera',
    description: 'Todo florece.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { color: '#86EFAC' },
    theme: 'primavera',
  },
  {
    key: 'badge_conejo',
    type: 'BADGE',
    name: 'Conejo',
    description: 'Saltarín.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'rabbit' },
    theme: 'primavera',
  },
  {
    key: 'badge_tulipan',
    type: 'BADGE',
    name: 'Tulipán',
    description: 'Color que renace.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'tulip' },
    theme: 'primavera',
  },
  {
    key: 'badge_brote',
    type: 'BADGE',
    name: 'Brote',
    description: 'Algo nuevo crece.',
    rarity: 'COMMON',
    priceBits: 150,
    data: { icon: 'seedling' },
    theme: 'primavera',
  },
  {
    key: 'frame_primavera',
    type: 'FRAME',
    name: 'Primavera',
    description: 'Marco floral.',
    rarity: 'RARE',
    priceBits: 600,
    data: { ring: 'linear-gradient(135deg,#86EFAC,#F9A8D4)' },
    theme: 'primavera',
  },
  {
    key: 'bg_primavera',
    type: 'BACKGROUND',
    name: 'Jardín',
    description: 'Verde que renace.',
    rarity: 'COMMON',
    priceBits: 250,
    data: { background: 'linear-gradient(160deg,#14241a,#241a24)' },
    theme: 'primavera',
  },

  // === Año Nuevo Lunar ===
  {
    key: 'title_ano_lunar',
    type: 'TITLE',
    name: 'Año del Dragón',
    description: 'Fuerza y fortuna.',
    rarity: 'RARE',
    priceBits: 550,
    data: { color: '#EF4444' },
    theme: 'ano_lunar',
  },
  {
    key: 'badge_farol',
    type: 'BADGE',
    name: 'Farol',
    description: 'Luz de la fortuna.',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'lantern' },
    theme: 'ano_lunar',
  },
  {
    key: 'badge_dragon',
    type: 'BADGE',
    name: 'Dragón',
    description: 'Poder ancestral.',
    rarity: 'EPIC',
    priceBits: 1200,
    data: { icon: 'dragon' },
    theme: 'ano_lunar',
  },
  {
    key: 'frame_lunar',
    type: 'FRAME',
    name: 'Año Lunar',
    description: 'Rojo y oro de la suerte.',
    rarity: 'RARE',
    priceBits: 650,
    data: { ring: 'linear-gradient(135deg,#DC2626,#FFD700)' },
    theme: 'ano_lunar',
  },
  {
    key: 'bg_lunar',
    type: 'BACKGROUND',
    name: 'Festival',
    description: 'Noche de faroles.',
    rarity: 'RARE',
    priceBits: 700,
    data: { background: 'linear-gradient(160deg,#2e0f0f,#2e1f0f)' },
    theme: 'ano_lunar',
  },

  // === Carnaval ===
  {
    key: 'badge_mascara',
    type: 'BADGE',
    name: 'Máscara',
    description: 'Que empiece la fiesta.',
    rarity: 'RARE',
    priceBits: 500,
    data: { icon: 'mask' },
    theme: 'carnaval',
  },
  {
    key: 'badge_confeti',
    type: 'BADGE',
    name: 'Confeti',
    description: 'Color por todas partes.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { icon: 'confetti' },
    theme: 'carnaval',
  },

  // === Más títulos meme / internet ===
  {
    key: 'title_based',
    type: 'TITLE',
    name: 'Based',
    description: 'Fiel a ti mismo.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#F59E0B' },
    theme: 'meme',
  },
  {
    key: 'title_rizz',
    type: 'TITLE',
    name: 'Rizz',
    description: 'Carisma nivel dios.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#F472B6' },
    theme: 'meme',
  },
  {
    key: 'title_sigma',
    type: 'TITLE',
    name: 'Modo Sigma',
    description: 'A tu propio ritmo.',
    rarity: 'RARE',
    priceBits: 500,
    data: { color: '#A8A8B0' },
    theme: 'meme',
  },
  {
    key: 'title_no_cap',
    type: 'TITLE',
    name: 'No Cap',
    description: 'Sin mentiras.',
    rarity: 'COMMON',
    priceBits: 200,
    theme: 'meme',
  },
  {
    key: 'title_404',
    type: 'TITLE',
    name: '404',
    description: 'Título no encontrado.',
    rarity: 'COMMON',
    priceBits: 200,
    data: { color: '#6B6B73' },
    theme: 'meme',
  },
  // === Marcos Legendarios (imagen) — Elementos ===
  {
    key: 'frame_fuego',
    type: 'FRAME',
    name: 'Fuego',
    description: 'El elemento ardiente.',
    rarity: 'LEGENDARY',
    priceBits: 3000,
    data: { image: '/cosmetics/frames/Fuego.png' },
    theme: 'elemento',
  },
  {
    key: 'frame_agua',
    type: 'FRAME',
    name: 'Agua',
    description: 'El elemento fluido.',
    rarity: 'LEGENDARY',
    priceBits: 3000,
    data: { image: '/cosmetics/frames/Agua.png' },
    theme: 'elemento',
  },
  {
    key: 'frame_tierra',
    type: 'FRAME',
    name: 'Tierra',
    description: 'El elemento firme.',
    rarity: 'LEGENDARY',
    priceBits: 3000,
    data: { image: '/cosmetics/frames/Tierra.png' },
    theme: 'elemento',
  },
  {
    key: 'frame_viento',
    type: 'FRAME',
    name: 'Viento',
    description: 'El elemento libre.',
    rarity: 'LEGENDARY',
    priceBits: 3000,
    data: { image: '/cosmetics/frames/Viento.png' },
    theme: 'elemento',
  },
];

export const COLOR_PALETTES = [
  {
    key: 'palette_exotica',
    name: 'Paleta Exótica',
    description: 'Los cinco colores exóticos, con descuento.',
    bundlePriceBits: 950,
    colorKeys: [
      'color_tornasol_fuego',
      'color_tornasol_oceano',
      'color_plata',
      'color_oro',
      'color_arcoiris',
    ],
  },
  {
    key: 'palette_neon',
    name: 'Paleta Neón',
    description: 'Synthwave, Vaporwave y Galaxia.',
    bundlePriceBits: 550,
    colorKeys: ['color_synthwave', 'color_vaporwave', 'color_galaxia'],
  },
  {
    key: 'palette_elementos',
    name: 'Paleta Elementos',
    description: 'Lava, Otoño y Aurora.',
    bundlePriceBits: 550,
    colorKeys: ['color_lava', 'color_otono', 'color_aurora'],
  },
];

export const BIT_PACKAGES = [
  {
    key: 'bits_punado',
    name: 'Puñado de Bits',
    bits: 100,
    bonus: 0,
    priceCents: 99,
  },
  {
    key: 'bits_bolsa',
    name: 'Bolsa de Bits',
    bits: 550,
    bonus: 50,
    priceCents: 499,
  },
  {
    key: 'bits_cofre',
    name: 'Cofre de Bits',
    bits: 1200,
    bonus: 200,
    priceCents: 999,
  },
  {
    key: 'bits_baul',
    name: 'Baúl de Bits',
    bits: 2600,
    bonus: 600,
    priceCents: 1999,
  },
  {
    key: 'bits_tesoro',
    name: 'Tesoro de Bits',
    bits: 7000,
    bonus: 2000,
    priceCents: 4999,
  },
];

export const SEASON_WINDOWS: Record<
  string,
  { months: number[]; label: string }
> = {
  san_valentin: { months: [2], label: 'San Valentín' },
  carnaval: { months: [2, 3], label: 'Carnaval' },
  primavera: { months: [3, 4, 5], label: 'Primavera' },
  verano: { months: [6, 7, 8], label: 'Verano' },
  otono: { months: [9, 10, 11], label: 'Otoño' },
  halloween: { months: [10], label: 'Halloween' },
  dia_muertos: { months: [10, 11], label: 'Día de Muertos' },
  invierno: { months: [12, 1, 2], label: 'Invierno' },
  navidad: { months: [12], label: 'Navidad' },
  ano_nuevo: { months: [12, 1], label: 'Año Nuevo' },
  ano_lunar: { months: [1, 2], label: 'Año Lunar' },
};

// Cuando varias temporadas se solapan (ej. octubre), esta es la que da nombre a la sección
export const SEASON_LABEL_PRIORITY: string[] = [
  'navidad',
  'halloween',
  'dia_muertos',
  'san_valentin',
  'ano_nuevo',
  'ano_lunar',
  'carnaval',
  'primavera',
  'verano',
  'otono',
  'invierno',
];

// Ofertas del día: cuántos items se rebajan y los posibles descuentos
export const OFFER_COUNT = 3;
export const OFFER_DISCOUNTS = [0.2, 0.3, 0.4];
