const ICONS: Record<string, string> = {
  crown: "👑",
  star: "⭐",
  heart: "❤️",
  cat: "🐱",
  bolt: "⚡",
  rocket: "🚀",
  fire: "🔥",
  trophy: "🏆",
  diamond: "💎",
  pumpkin: "🎃",
  ghost: "👻",
  skull: "💀",
  snowflake: "❄️",
  gift: "🎁",
  clover: "🍀",
  alien: "👽",
  rainbow: "🌈",
  flower: "🌸",
  heartarrow: "💘",
  twohearts: "💕",
  rose: "🌹",
  sun: "☀️",
  palm: "🌴",
  icecream: "🍦",
  fireworks: "🎆",
  party: "🎉",
  champagne: "🍾",
  rabbit: "🐰",
  tulip: "🌷",
  seedling: "🌱",
  lantern: "🏮",
  dragon: "🐉",
  mask: "🎭",
  confetti: "🎊",
};

export function badgeIcon(icon?: string): string {
  return (icon && ICONS[icon]) || "🏅";
}
