export const COUNTRIES: { code: string; name: string; dialCode: string }[] = [
  { code: "MX", name: "México", dialCode: "+52" },
  { code: "AR", name: "Argentina", dialCode: "+54" },
  { code: "BO", name: "Bolivia", dialCode: "+591" },
  { code: "CL", name: "Chile", dialCode: "+56" },
  { code: "CO", name: "Colombia", dialCode: "+57" },
  { code: "CR", name: "Costa Rica", dialCode: "+506" },
  { code: "CU", name: "Cuba", dialCode: "+53" },
  { code: "DO", name: "República Dominicana", dialCode: "+1" },
  { code: "EC", name: "Ecuador", dialCode: "+593" },
  { code: "SV", name: "El Salvador", dialCode: "+503" },
  { code: "ES", name: "España", dialCode: "+34" },
  { code: "GT", name: "Guatemala", dialCode: "+502" },
  { code: "HN", name: "Honduras", dialCode: "+504" },
  { code: "NI", name: "Nicaragua", dialCode: "+505" },
  { code: "PA", name: "Panamá", dialCode: "+507" },
  { code: "PY", name: "Paraguay", dialCode: "+595" },
  { code: "PE", name: "Perú", dialCode: "+51" },
  { code: "PR", name: "Puerto Rico", dialCode: "+1" },
  { code: "UY", name: "Uruguay", dialCode: "+598" },
  { code: "VE", name: "Venezuela", dialCode: "+58" },
  { code: "US", name: "Estados Unidos", dialCode: "+1" },
  { code: "CA", name: "Canadá", dialCode: "+1" },
  { code: "BR", name: "Brasil", dialCode: "+55" },
  { code: "GB", name: "Reino Unido", dialCode: "+44" },
  { code: "FR", name: "Francia", dialCode: "+33" },
  { code: "DE", name: "Alemania", dialCode: "+49" },
  { code: "IT", name: "Italia", dialCode: "+39" },
  { code: "PT", name: "Portugal", dialCode: "+351" },
  { code: "NL", name: "Países Bajos", dialCode: "+31" },
  { code: "BE", name: "Bélgica", dialCode: "+32" },
  { code: "CH", name: "Suiza", dialCode: "+41" },
  { code: "AT", name: "Austria", dialCode: "+43" },
  { code: "SE", name: "Suecia", dialCode: "+46" },
  { code: "NO", name: "Noruega", dialCode: "+47" },
  { code: "DK", name: "Dinamarca", dialCode: "+45" },
  { code: "FI", name: "Finlandia", dialCode: "+358" },
  { code: "IE", name: "Irlanda", dialCode: "+353" },
  { code: "PL", name: "Polonia", dialCode: "+48" },
  { code: "RU", name: "Rusia", dialCode: "+7" },
  { code: "UA", name: "Ucrania", dialCode: "+380" },
  { code: "GR", name: "Grecia", dialCode: "+30" },
  { code: "CN", name: "China", dialCode: "+86" },
  { code: "JP", name: "Japón", dialCode: "+81" },
  { code: "KR", name: "Corea del Sur", dialCode: "+82" },
  { code: "IN", name: "India", dialCode: "+91" },
  { code: "ID", name: "Indonesia", dialCode: "+62" },
  { code: "TH", name: "Tailandia", dialCode: "+66" },
  { code: "VN", name: "Vietnam", dialCode: "+84" },
  { code: "PH", name: "Filipinas", dialCode: "+63" },
  { code: "MY", name: "Malasia", dialCode: "+60" },
  { code: "SG", name: "Singapur", dialCode: "+65" },
  { code: "TR", name: "Turquía", dialCode: "+90" },
  { code: "IL", name: "Israel", dialCode: "+972" },
  { code: "SA", name: "Arabia Saudita", dialCode: "+966" },
  { code: "AE", name: "Emiratos Árabes Unidos", dialCode: "+971" },
  { code: "AU", name: "Australia", dialCode: "+61" },
  { code: "NZ", name: "Nueva Zelanda", dialCode: "+64" },
  { code: "ZA", name: "Sudáfrica", dialCode: "+27" },
  { code: "NG", name: "Nigeria", dialCode: "+234" },
  { code: "EG", name: "Egipto", dialCode: "+20" },
  { code: "MA", name: "Marruecos", dialCode: "+212" },
];

export function countryCodeToFlag(code: string): string {
  return code
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

export function countryName(code: string): string {
  return COUNTRIES.find((c) => c.code === code)?.name ?? code;
}
